# Generated by Django 3.2.6 on 2021-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
