# Generated by Django 3.2.6 on 2021-11-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_auto_20211029_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'direcciones'},
        ),
    ]
