# Generated by Django 3.2.6 on 2021-08-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={},
        ),
    ]
