# Generated by Django 3.2.6 on 2021-08-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_alter_organizacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='descripcion',
            field=models.CharField(help_text='Descripcion de clinica', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.CharField(help_text='Descripcion de organizacion', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='descripcion',
            field=models.CharField(help_text='Descripcion de Veterinario', max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
