# Generated by Django 3.2.6 on 2021-10-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
        ('organizaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.OneToOneField(help_text='Calle número, departamento, localidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.direccion'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
