# Generated by Django 3.2.6 on 2021-11-16 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_veterinario_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='calificacion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
