# Generated by Django 3.2.6 on 2021-08-24 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_auto_20210821_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name_plural': 'organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'verbose_name_plural': 'veterinarios'},
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='clinica',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número de celular válido para Argentina', regex='/^(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}$/')]),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='cuit',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
