# Generated by Django 3.2.6 on 2021-08-24 22:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_auto_20210821_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.pais')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.ciudad'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.departamento'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.pais'),
        ),
    ]
