# Generated by Django 3.2.6 on 2021-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_alter_organizacion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='direccion',
            field=models.TextField(help_text='Ejemplo: Maipu 123, Godoy Cruz, Mendoza', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='direccion',
            field=models.CharField(help_text='Ejemplo: Maipu 123, Godoy Cruz, Mendoza', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='direccion',
            field=models.CharField(help_text='Ejemplo: Maipu 123, Godoy Cruz, Mendoza', max_length=20, null=True),
        ),
    ]
