# Generated by Django 3.2.6 on 2021-08-24 23:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_auto_20210824_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='pais',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.pais'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.ciudad'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.ciudad'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ciudad', chained_model_field='ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.departamento'),
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
    ]
