# Generated by Django 3.2.6 on 2021-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_auto_20210824_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='apellido',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
