# Generated by Django 3.2.6 on 2021-11-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_alter_veterinario_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='calificacion_total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
