# Generated by Django 3.2.6 on 2021-09-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0005_auto_20210824_2310'),
        ('organizaciones', '0005_auto_20210826_0139'),
    ]

    operations = [
    ]
