# Generated by Django 3.2.6 on 2021-09-08 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0005_auto_20210826_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='cuit',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='whatsapp',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='cuit',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(default='', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='whatsapp',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
    ]
