# Generated by Django 3.2.6 on 2021-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0005_auto_20211029_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='direccion',
            field=models.CharField(help_text='Ejemplo: Maipu 123, Godoy Cruz, Mendoza', max_length=20, null=True),
        ),
    ]
