# Generated by Django 3.2.6 on 2021-09-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0006_auto_20210908_2330'),
        ('organizaciones', '0006_merge_0005_auto_20210824_2310_0005_auto_20210826_0139'),
    ]

    operations = [
    ]
