# Generated by Django 3.2.6 on 2021-09-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0007_merge_20210912_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='pais',
        ),
    ]
