# Generated by Django 3.2.6 on 2021-09-15 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0007_merge_20210915_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='pais',
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cuit',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(default='', help_text='Ejemplo: 2614247398', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='whatsapp',
            field=models.CharField(help_text='Ejemplo: 26127483945', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='cuit',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(default='', help_text='Ejemplo: 2614247398', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='whatsapp',
            field=models.CharField(help_text='Ejemplo: 2614247398', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número válido para Argentina', regex='(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}')]),
        ),
    ]
