# Generated by Django 3.2.6 on 2021-11-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0011_auto_20211104_2236'),
        ('organizaciones', '0011_auto_20211104_2302'),
    ]

    operations = [
    ]
