# Generated by Django 3.2.6 on 2021-12-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='EstadoSolicitudInsumo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin Validar'), (1, 'Validado'), (2, 'Rechazado')], default='0'),
        ),
    ]
