# Generated by Django 3.2.6 on 2021-11-04 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_solicitud_insumo_detalle',
            name='estado_Solicitud_Insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.estado_solicitud_insumo'),
        ),
        migrations.AddField(
            model_name='estado_solicitud_monetaria_detalle',
            name='Estado_Solicitud_Monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.estado_solicitud_monetaria'),
        ),
        migrations.AlterField(
            model_name='estado_solicitud_insumo_detalle',
            name='fecha_desde',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estado_solicitud_monetaria_detalle',
            name='fecha_desde',
            field=models.DateField(auto_now_add=True),
        ),
    ]
