# Generated by Django 3.2.6 on 2021-11-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='pedido',
            field=models.ImageField(blank=True, null=True, upload_to='solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='pedido',
            field=models.ImageField(blank=True, null=True, upload_to='solicitud'),
        ),
    ]
