# Generated by Django 3.2.6 on 2021-11-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_auto_20211104_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='Estado_Solicitud_Monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.estado_solicitud_monetaria_detalle'),
        ),
    ]
