# Generated by Django 3.2.6 on 2021-12-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_solicitud_donacion_insumo_estadosolicitudinsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='EstadoSolicitudMonetaria',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin Validar'), (1, 'Validado'), (2, 'Rechazado')], default='0'),
        ),
    ]
