# Generated by Django 3.2.6 on 2021-12-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='EstadoSolicitudInsumo',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='EstadoSolicitudMonetaria',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
