# Generated by Django 3.2.6 on 2021-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='cbu',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='nombre_banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
