# Generated by Django 3.2.6 on 2021-11-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_solicitud_donacion_monetaria_estado_solicitud_monetaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_solicitud_monetaria_detalle',
            old_name='Estado_Solicitud_Monetaria',
            new_name='estado_Solicitud_Monetaria',
        ),
        migrations.RenameField(
            model_name='solicitud_donacion_monetaria',
            old_name='Estado_Solicitud_Monetaria',
            new_name='estado_Solicitud_Monetaria',
        ),
    ]
