# Generated by Django 3.2.6 on 2021-11-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_auto_20211105_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_donacion_monetaria',
            name='estado_Solicitud_Monetaria',
        ),
        migrations.AddField(
            model_name='estado_solicitud_monetaria_detalle',
            name='solicitud_Donacion_Monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud_donacion_monetaria'),
        ),
    ]
