# Generated by Django 3.2.6 on 2021-12-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20211121_2024'),
        ('solicitud', '0004_alter_solicitud_donacion_monetaria_nombre_banco'),
    ]

    operations = [
    ]
