# Generated by Django 3.2.6 on 2021-09-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(default='', help_text='Ingrese su dni', max_length=20, unique=True),
        ),
    ]
