# Generated by Django 3.2.6 on 2021-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ejemplo: Maipu 123, Godoy Cruz, Mendoza', max_length=100, null=True),
        ),
    ]
