# Generated by Django 3.2.6 on 2021-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210908_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(help_text='Ingrese su dni', max_length=20),
        ),
    ]
