# Generated by Django 3.2.6 on 2021-11-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_email_verified',
        ),
    ]
