# Generated by Django 3.2.6 on 2021-09-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.IntegerField(error_messages={'max_length': 'El dni debe tener 8 caracteres'}, max_length=8),
        ),
    ]
