# Generated by Django 3.2.6 on 2021-11-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(message='El formato de DNI debe tener 8 caracteres numericos', regex='^[\\d]{1,3}\\.?[\\d]{3,3}\\.?[\\d]{3,3}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuario'),
        ),
    ]
