# Generated by Django 3.2.6 on 2021-09-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210910_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
