# Generated by Django 3.2.6 on 2021-09-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(default='', max_length=8),
        ),
    ]
