# Generated by Django 3.2.6 on 2021-09-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210824_2254'),
        ('usuario', '0007_alter_usuario_dni'),
    ]

    operations = [
    ]
