<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-15 22:20
=======
# Generated by Django 3.2.6 on 2021-09-14 00:01
>>>>>>> d868d51 (create login con facebook)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210824_2254'),
        ('usuario', '0007_alter_usuario_dni'),
    ]

    operations = [
    ]
