# Generated by Django 3.2.6 on 2021-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20211107_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='permiso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
