# Generated by Django 3.2.6 on 2021-11-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0012_auto_20211107_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_type',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
