# Generated by Django 3.2.6 on 2021-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20211107_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permiso',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
