# Generated by Django 3.2.6 on 2021-11-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_usuario_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permiso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuario'), (2, 'Veterinario'), (3, 'Organizacion'), (4, 'Clinicas')], default=1, null=True),
        ),
    ]
