# Generated by Django 3.2.6 on 2021-11-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_usuario_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permiso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuario'), (2, 'Veterinario'), (3, 'Organizacion'), (4, 'Clinica')], default=1, null=True),
        ),
    ]
