# Generated by Django 3.2.6 on 2021-10-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_cantidad_insumo_solicitud_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='um',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='um',
        ),
    ]
