# Generated by Django 3.2.6 on 2021-11-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donacionV2', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidad_insumo_donacion',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
    ]
