# Generated by Django 3.2.6 on 2021-12-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '__first__'),
        ('donacionV2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidad_insumo_donacion',
            name='donacion_isumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacionV2.donacion_insumo'),
        ),
        migrations.AddField(
            model_name='cantidad_insumo_donacion',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
    ]
