# Generated by Django 3.2.6 on 2021-11-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitud', '0001_initial'),
        ('donacionV2', '0002_cantidad_insumo_donacion_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion_monetaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(max_length=100)),
                ('solicitud_monetaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud_donacion_insumo')),
                ('uc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'donaciones_monetaria',
            },
        ),
    ]
