# Generated by Django 3.2.6 on 2021-12-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacionV2', '0002_auto_20211205_2246'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion_insumo',
            name='solicitud_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud_donacion_insumo'),
        ),
    ]
