# Generated by Django 3.2.6 on 2021-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacionV2', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio_pago',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pagos'),
        ),
    ]
