# Generated by Django 3.2.6 on 2021-11-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
        ('donacionV2', '0003_donacion_monetaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion_monetaria',
            name='solicitud_monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud_donacion_monetaria'),
        ),
    ]
