# Generated by Django 3.2.6 on 2021-12-05 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacionV2', '0003_donacion_insumo_solicitud_insumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion_insumo',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donacion_monetaria',
            name='solicitud_monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud_donacion_monetaria'),
        ),
        migrations.AddField(
            model_name='donacion_monetaria',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_donacion_insumo',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_donacion_insumo_detalle',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_donacion_monetaria',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_donacion_monetaria_detalle',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medio_pago',
            name='uc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
