# Generated by Django 3.2.6 on 2021-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacionV2', '0005_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio_pago',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pothos'),
        ),
    ]
