# Generated by Django 3.2.6 on 2021-11-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacionV2', '0005_alter_donacion_monetaria_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion_monetaria',
            name='comprobante',
            field=models.FileField(default='', upload_to='comprobante'),
            preserve_default=False,
        ),
    ]
