# Generated by Django 3.2.6 on 2021-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Donacion_Insumos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('tipo_donacion', models.TextField(max_length=10)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Donacion_Monetaria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100, null=True)),
                ('tipo_donacion', models.TextField(max_length=10, null=True)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
    ]
