# Generated by Django 3.2.6 on 2021-10-22 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donacion', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.veterinario'),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.veterinario'),
        ),
        migrations.AddField(
            model_name='medio_pago',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_solicitud_monetaria',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado_solicitud_insumo',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donacion_monetaria',
            name='solicitud_monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.solicitud_donacion_monetaria'),
        ),
        migrations.AddField(
            model_name='donacion_monetaria',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donacion_insumo',
            name='solicitud_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.solicitud_donacion_insumo'),
        ),
        migrations.AddField(
            model_name='donacion_insumo',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cantidad_insumo',
            name='donacion_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion_insumo'),
        ),
        migrations.AddField(
            model_name='cantidad_insumo',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.insumo'),
        ),
        migrations.AddField(
            model_name='cantidad_insumo',
            name='solicitud_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.solicitud_donacion_insumo'),
        ),
        migrations.AddField(
            model_name='cantidad_insumo',
            name='uc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
