# Generated by Django 3.2.6 on 2021-08-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud_Donacion_Insumos',
            new_name='Solicitud_Donacion_Insumo',
        ),
    ]
