# Generated by Django 3.2.6 on 2021-10-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion_monetaria',
            name='solicitud_monetaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.solicitud_donacion_monetaria'),
        ),
    ]
