# Generated by Django 3.2.6 on 2021-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='cantidad_insumo',
            name='um',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='um',
        ),
        migrations.AlterField(
            model_name='cantidad_insumo',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cantidad_insumo',
            name='donacion_insumo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cantidad_insumo',
            name='insumo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cantidad_insumo',
            name='solicitud_insumo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
