# Generated by Django 3.2.6 on 2021-10-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0002_donacion_monetaria_solicitud_monetaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidad_insumo',
            name='donacion_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion_insumo'),
        ),
    ]
