# Generated by Django 3.2.6 on 2021-09-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donacion', '0002_rename_solicitud_donacion_insumos_solicitud_donacion_insumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud_donacion_insumo',
            options={'verbose_name_plural': 'solicitudes_insumos'},
        ),
        migrations.AlterModelOptions(
            name='solicitud_donacion_monetaria',
            options={'verbose_name_plural': 'solicitudes_monetarias'},
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='fm',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='pedido',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='uc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_insumo',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='fm',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='monto',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='pedido',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='uc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud_donacion_monetaria',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='tipo_donacion',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='titulo',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Estado_Solicitud_Monetaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('uc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'estados_solicitudes_monetarias',
            },
        ),
        migrations.CreateModel(
            name='Estado_Solicitud_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('uc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'estados_solicitudes_insumos',
            },
        ),
    ]
