# Generated by Django 3.2.6 on 2021-09-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_auto_20210914_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='titulo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_monetaria',
            name='titulo',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
