# Generated by Django 3.2.6 on 2021-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_auto_20211023_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='um',
        ),
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='veterinario',
            field=models.TextField(max_length=100),
        ),
    ]
