# Generated by Django 3.2.6 on 2021-09-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0004_auto_20210929_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='cant_insumo',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.cantidad_insumo'),
        ),
    ]
