# Generated by Django 3.2.6 on 2021-09-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0005_alter_solicitud_donacion_insumo_cant_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_donacion_insumo',
            name='cant_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donacion.cantidad_insumo'),
        ),
    ]
