# Generated by Django 3.2.6 on 2021-10-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0006_alter_solicitud_donacion_insumo_cant_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_donacion_insumo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='solicitud_donacion_monetaria',
            name='fecha',
        ),
    ]
